#!/usr/bin/python3

import os
import subprocess
import time

key=""
data={}
#The data file is saved dafultly at ~/.dmenu_data
file_path=os.getenv("HOME")+'/.dmenu_data'

#Read the data file
with open(file_path,'r') as data_file:
    for i in data_file:
        tmp=i[:-1].split(';')
        if len(tmp)==2:
            data[tmp[1]]=[int(tmp[0])]
        else:
            data[tmp[1]]=[int(tmp[0]),tmp[2]]
        key=key+tmp[1]+'\n'

user_select=os.popen(' echo "'+key[:-1]+'"|dmenu')
user=user_select.read()

if not user:
    quit()

#Attempt to run the command
if (user in data)and (len(data[user])==2):
    #You can do some alias in the format like
    #  10;na;nautilus --nodesktop
    #at the data file
    try_run=subprocess.Popen(data[user][1],shell=True)
else:
    try_run=subprocess.Popen(user,shell=True)

#Some softwares will not giva back a code about the status. So if it run more than 0.1 second, we think it runs well.
time.sleep(0.1)
if not try_run.poll():
    if user in data:
        data[user][0]+=1
    else:
        data[user]=[1]

#Write the data file
with open(file_path,'w') as data_file:
    for i in data:
        tmp=data[i]
        if len(tmp)==2:
            print(str(tmp[0])+';'+i+';'+tmp[1],file=data_file)
        else:
            print(str(tmp[0])+';'+i,file=data_file)

#Sort the software you used based on times
os.system("sort -r -n -k 1 -t \; "+file_path+" -o "+file_path)
